# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alexandrea Stylianou
tagline: Integrating Clinical Expertise & Medical Software Delivery
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Hi there, thanks for stopping by! 
<br>
I am a Bioinformatic Programmer and Registered Nurse.
My studies have granted me an in depth knowledge of disease pathophysiology, health care, molecular biology, proteomics and genomics. 
My technical experiences include object oriented programming, algorithm development and efficiently solving problems.
I have worked on a number of projects and have been successful in implementing stakeholder and providing deliverables.
I am known to be intuitive, optimistic, purposeful, inclusive, detail-oriented and embrace change readily.
Outside work I love exercising, reading, and solving puzzles. Feel free to contact me if you have any questions about my work experience or academic projects.'

#sidebar links
email: styalex3@gmail.com
linkedin: alex-stylianou
github: a-rhodes-vcu
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
